name: AndroidBuild
on:
  pull_request:
    branches : [master]
  push:
    branches : [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v3


      - name: upload build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Face Detection.apk
          path: \app\build\outputs\apk\debug\app-debug.apk

      - name: "Run UI Tests"
        uses: vgaidarji/android-github-actions-emulator@v1.0.1



#name: AndroidBuild
#on:
#  pull_request:
#    branches: [master]
#  push:
#    branches: [master]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4.1.0
#
#      - name: Setup Java JDK
#        uses: actions/setup-java@v3.13.0
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v3
#
#      - name: Upload Build Artifact
#        uses: actions/upload-artifact@v3.1.3
#        with:
#          name: Face Detection.apk
#          path: app/build/outputs/debug/app-debug.apk
#
#      - name: Set up emulator
#        uses: android/setup-emulator@v2
#        with:
#          api-level: 34
#          package: system-images;android-34;google_apis;x86
#          script: |
#            echo no | avdmanager create avd --force -n test -k "system-images;android-34;google_apis;x86" --device "pixel"
#
#      - name: Start emulator
#        uses: android/emulator-runner@v2
#        with:
#          api-level: 34
#          emulator-start-options: '-no-snapshot'
#          script: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
#
#      - name: Run tests
#        uses: android/run-tests@v2
#        with:
#          test-targets: 'connectedAndroidTest'
