name: AndroidBuild
on:
  pull_request:
    branches : [master]
  push:
    branches : [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permissions for gradlew //this step is only for macOS
        run: chmod +x ./gradlew 

      - name: Build with Gradle
        run: ./gradlew build

        #Setup Gradle Cache to improve the speed of the workflows

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Setup gradle
        uses: gradle/gradle-build-action@v3


      - name: upload build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Face_Detection.apk
          path: \app\build\outputs\apk\debug\app-debug.apk

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck


