name: Android Tests

on:
  push:
    branches: [FD_v1.0.1]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [ 29 ]
        os: [ ubuntu-latest ]

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permissions for gradlew //this step is only for macOS
        run: chmod +x ./gradlew


      - name: Enable KVM
        run: |
          echo avdmanager list avd
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm


      - name: Start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck


      - name: Upload Instrumentation test report
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation_test_report
          path: app\build\reports\androidTests\connected

#      - name: Set up Android SDK
#        uses: actions/setup-java@v2
#        with:
#          java-version: '21'
#          distribution: 'adopt'
#
#      - name: Install Android SDK
#        run: |
#          echo y | sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3" "system-images;android-29;default;x86"
#
#      - name: Create Android Emulator
#        run: echo no | avdmanager create avd -n test -k "system-images;android-29;default;x86"
#
#      - name: Start Emulator
#        run:     $ANDROID_HOME/emulator/emulator -avd Pixel_8_Pro_API_VanillaIceCream -no-audio -no-window -accel auto -gpu swiftshader_indirect
#
#
#      - name: Wait for Emulator to be ready
#        run: |A
#          adb wait-for-device
#          adb shell input keyevent 82


