name: ReleaseBuild
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permissions for gradlew //this step is only for macOS
        run: chmod +x ./gradlew

      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.FACEKEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.FACEPASSWORD }}

      - name: Upload Bundle
        uses: actions/upload-artifact@v2
        with:
          name: release.aab
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}